name: CI
run-name: >-
  ${{
    join(fromJSON(format('["{0}", "{1}", "{2}"]',
      ((inputs.tools_make_branch != '' && inputs.tools_make_branch != 'master') || inputs.tools_windows_msvc_branch != '') && github.workflow || '',
      (inputs.tools_make_branch != '' && inputs.tools_make_branch != 'master') && format('tools-make: {0}', inputs.tools_make_branch) || '',
      inputs.tools_windows_msvc_branch != '' && format('tools-windows-msvc: {0}', inputs.tools_windows_msvc_branch) || ''
    )), ' ')
  }}

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      tools_make_branch:
        description: "tools-make branch"
        default: "master"
        required: true
      tools_windows_msvc_branch:
        description: "tools-windows-msvc branch (leave empty to use latest pre-built release)"
        required: false

env:
  APT_PACKAGES: >-
    git
    cmake
    clang
    pkg-config
    libgnutls28-dev
    libffi-dev
    libicu-dev
    libxml2-dev
    libxslt1-dev
    libssl-dev
    libavahi-client-dev
    zlib1g-dev
    gnutls-bin
    libcurl4-gnutls-dev

  # packages for GCC Objective-C runtime
  APT_PACKAGES_gcc: >-
    libobjc-10-dev
    libblocksruntime-dev
    gobjc

  # packages for libobjc2 / libdispatch
  APT_PACKAGES_clang: >-
    libpthread-workqueue-dev

  RPM_PACKAGES: >-
    which
    gzip
    findutils
    git
    cmake
    clang
    lld
    pkg-config
    gnutls-devel
    gnutls-utils
    libcurl-devel
    libffi-devel
    libicu-devel
    libxml2-devel
    libxslt-devel
    glibc-gconv-extra

  # GNUstep Windows MSVC toolchain release tag to be used (keep up to date with latest release):
  # https://github.com/gnustep/tools-windows-msvc/releases
  TOOLS_WINDOWS_MSVC_RELEASE_TAG: latest

jobs:
  ########### Linux ###########
  linux:
    name: ${{ matrix.name }}
    container: ${{ matrix.container }}
    runs-on: ubuntu-latest
    # don't run pull requests from local branches twice
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Rocky Linux 8 x64 Clang gnustep-2.2
            container: rockylinux:8
            library-combo: ng-gnu-gnu
            runtime-version: gnustep-2.2
            CC: clang
            CXX: clang++
            libdir: lib64

    env:
      SRC_PATH: ${{ github.workspace }}/source
      DEPS_PATH: ${{ github.workspace }}/dependencies
      INSTALL_PATH: ${{ github.workspace }}/build
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      LIBRARY_COMBO: ${{ matrix.library-combo }}
      RUNTIME_VERSION: ${{ matrix.runtime-version }}
      LIBDIR: ${{ matrix.libdir }}

    defaults:
      run:
        working-directory: ${{ env.SRC_PATH }}

    steps:
      - uses: actions/checkout@v7
        with:
          path: ${{ env.SRC_PATH }}

      - name: Install apt packages
        run: |
          apt-get -q -y update

          apt-get -q -y install $APT_PACKAGES $APT_PACKAGES_${{ matrix.library-combo == 'ng-gnu-gnu' && 'clang' || 'gcc' }}

          # gnustep-2.2 runtime requires ld.gold or lld
          if [ "$RUNTIME_VERSION" = "gnustep-2.2" ]; then
            update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.gold" 10
          fi
        if: ${{ startsWith(matrix.container, 'ubuntu') }}

      - name: Install rpm packages
        run: |
          yum install -y $RPM_PACKAGES

          # gnustep-2.2 runtime requires ld.gold or lld
          if [ "$RUNTIME_VERSION" = "gnustep-2.2" ]; then
            update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/lld" 10
          fi
        if: ${{ startsWith(matrix.container, 'rockylinux') }}

      - name: Install dependencies
        env:
          TOOLS_MAKE_BRANCH: ${{github.event.inputs.tools_make_branch}}
        run: ./.github/scripts/dependencies.sh

      - name: Build source
        run: |
          . $INSTALL_PATH/share/GNUstep/Makefiles/GNUstep.sh
          ./configure
          make -j$(nproc) && make install

      - name: Run tests
        run: |
          . $INSTALL_PATH/share/GNUstep/Makefiles/GNUstep.sh
          make check

      - name: Upload logs
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: Logs - ${{ matrix.name }}
          path: |
            source/config.log
            source/Tests/tests.log

